config/routes.rb
Rails.application.routes.draw do
  # get 'questions/index' - сгенерировано по умолчанию
  # localhost:3000/questions HTTP GET
  # app/views/questions/index.html.erb

  # resources :questions, only: %i[index new edit create update destroy show]
  # сегенерированы все методы

  resource :session, only: %i[new create destroy]
  resources :questions do
    # resources :answers, only: %i[create destroy]
    resources :answers, except: %i[create destroy]
  end

  resources :users do
    resources :users, only: %i[create new edit update]
  end

  # get '/questions', to: 'questions#index'

  # get 'pages/index' - сгенерировано по умолчанию
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # get '/question/new', to: 'questions#new'

  # post '/questions', to: 'questions#create'

  # get '/question/:id/edit', to: 'questions#edit'

  # get '/question/:id/show', to: 'questions#show'

  # Defines the root path route ("/")
  # Корневой маршрут, кторорый обращается к контроллеру pages
  # и вызывать там метод index
  root 'pages#index'
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # localhost/questons
  before_action :set_question!, only: %i[show edit update destroy]

  def index
    # @questions = Question.order(created_at: 'DESC').page params[:page]
    @pagy, @questions = pagy Question.order(created_at: 'DESC')
    @questions = @questions.decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = question_params

    @question = Question.new(question_params)
    if @question.save
      flash[:success] = 'Question created!'
      # flash[:expires] = Time.now + 5.seconds
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    # if @question.update(params[:id])
    #   redirect_to questions_path
    #   flash[:notice] = "Question updated"
    # else
    #   render :edit
    # end
  end

  def update
    if @question.update(question_params)
      flash[:success] = "Question updated!"
      redirect_to questions_path
      # flash[:notice] = 'Question updated'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:success] = "Question deleted!"
    redirect_to questions_path
  end

  def show
    @question = @question.decorate
    @answer = @question.answers.build
    @pagy, @answers = pagy @question.answers.order(created_at: 'DESC')
    @answers = @answers.decorate
    # 3 способа:
    # @answers = @question.answers.order(created_at: 'DESC').page(params[:page]).per(5)
    # @answers = Answer.where(question_id: params[:id]).order created_at: 'DESC'
    # @answers = Answer.where(question: @question).order created_at: 'DESC'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find params[:id]
  end
end

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>
<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'title', class: 'form-control' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit "Submit question", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<% currently_at 'Questions'%>
<% provide :page_title, 'Edit question' %>
<h1 class="mb-4">Edit question</h1>
<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions'%>
<h1 class="mb-4">Questions</h1>
<%= link_to 'new question', new_question_path, class: 'btn btn-primary btn-lg mb-3' %>
<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
<% @questions.each do |item| %>
  <article class="card my-3">
    <div class="card-body">
      <h2><%= item.title %></h2>
      <section class="card-text">
        <time datetime = "<%= item.formatted_created_at%>">
          <small><%= item.formatted_created_at %></small>
        </time>
        <p class="my-2"><%= truncate strip_tags(item.body), length: 100, omission: '...(continued)'%>
          <br>
          <%= link_to 'show', question_path(item), class: "btn btn-primary" %>
          <%= link_to 'edit', edit_question_path(item), class: "btn btn-secondary" %>
          <%= link_to 'Delete', question_path(item), class: "btn btn-danger", 
            data: { method: :delete, confirm: 'Are you sore?'} %>
        </p>
      </section>
    </div>
  </article>
<% end %>
<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>

app/views/questions/new.html.erb
<% provide :page_title, 'New question' %>
<% currently_at 'Questions'%>
<h1 class="mb-4">New question</h1>
<%= render 'form' %>

app/views/questions/show.html.erb
<% currently_at 'Questions'%>
<h1 class="mb-4"><%= @question.title %></h1>
<time datetime = "<%= @question.formatted_created_at%>">
  <%= @question.formatted_created_at %>
</time>
<div class="lead my-3">
  <%= sanitize @question.body %>
</div>
<%= link_to 'show', question_path(@question), class: "btn btn-primary" %>
<%= link_to 'edit', edit_question_path(@question), class: "btn btn-secondary" %>
<%= link_to 'Delete', question_path(@question), class: "btn btn-danger", 
            data: { method: :delete, confirm: 'Are you sore?'} %>
<hr class="my-3">
<div class="text-start">
  <h4 class="h-auto">Write your answer</h4>
</div>
<div>
  <%= render 'answers/form' %>
</div>
<h2 class="mt-5 mb-3">Answers</h2>
<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
<%= render partial: 'answers/answer', collection: @answers, 
  as: :answer, locals: {question: @question} %>
<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>