config/routes.rb
Rails.application.routes.draw do
  # get 'questions/index' - сгенерировано по умолчанию
  # localhost:3000/questions HTTP GET
  # app/views/questions/index.html.erb

  # resources :questions, only: %i[index new edit create update destroy show]
  # сегенерированы все методы

  resource :session, only: %i[new create destroy]
  resources :questions do
    # resources :answers, only: %i[create destroy]
    resources :answers, except: %i[create destroy]
  end

  resources :users do
    resources :users, only: %i[create new edit update]
  end

  # get '/questions', to: 'questions#index'

  # get 'pages/index' - сгенерировано по умолчанию
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # get '/question/new', to: 'questions#new'

  # post '/questions', to: 'questions#create'

  # get '/question/:id/edit', to: 'questions#edit'

  # get '/question/:id/show', to: 'questions#show'

  # Defines the root path route ("/")
  # Корневой маршрут, кторорый обращается к контроллеру pages
  # и вызывать там метод index
  root 'pages#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include ActionView::RecordIdentifer

  before_action :set_question!
  before_action :set_answer!, except: :create

  def update
    if @answer.update(answer_params)
      flash[:success] = "Answer updated!"
      redirect_to question_path(@question, anchor: dom_id(@answer))
      # flash[:notice] = 'Question updated'
    else
      render :edit
    end
  end

  def edit
  end

  def create
    # render plain: params
    @answer = @question.answers.build(answer_params)
    if @answer.save
      flash[:success] = "Answer saved!"
      redirect_to question_path(@question)
    else
      @answers = @question.answers.order(created_at: 'DESC')
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = "Answer deleted!"
    redirect_to question_path(@question)
  end

  private

  def set_question!
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_answer!
    @answer = @question.answers.find(params[:id])
  end
end

app/views/answers/_answer.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(answer) do %>
  <div class="card-body">
    <section class="card-text">
      <small> <time datetime = "<%= answer.formatted_created_at%>">
          <%= answer.formatted_created_at %>
        </time> </small>
      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>
    <%= link_to 'Edit', edit_question_answer_path(question, answer), 
            class: "btn btn-info btn-xs" %>
    <%= link_to 'Delete', question_answer_path(question, answer), 
            class: "btn btn-danger btn-xs", 
        data: { method: :delete, confirm: 'Are you sure?' } %>
  </div>
<% end %>

app/views/answers/_form.html.erb
<div>
  <%= render 'shared/errors', object: @answer %>
</div>
<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit "Submit answer", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% currently_at 'Answers'%>
<% provide :page_title, 'Edit answer' %>
<h1>Edit answer</h1>
<div>
  <%= render 'form' %>
</div>